name: earthquake_testbed
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip:
      # pip-only packages
      - patchify
      - segmentation-models-pytorch
      - torcheval
      - optuna-dashboard
