name: earthquake_testbed
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - fastai
  - monai
  - optuna
  - optuna-integration
  - seaborn
  - jupyter
  - lightning
  - pip:
      # pip-only packages
      - patchify
      - segmentation-models-pytorch
      - torcheval
